spring.application.name=portfolio-backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://pardeshisai12_db_user:Admin1234@cluster0.hrjz3p4.mongodb.net/portfolio?retryWrites=true&w=majority
spring.data.mongodb.database=portfolio

jwt.secret=YourSuperSecretKeyChangeThisInProduction1234567890ABCDEF
jwt.expiration=86400000

admin.username=admin
admin.password=admin@123

cors.allowed-origins=http://localhost:3000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB